version: "3"
services:
  dev-database:
    container_name: dev-database
    image: "postgres:11.5-alpine"
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: zan
      POSTGRES_PASSWORD: zan
      POSTGRES_MULTIPLE_DATABASES: dev, test
    volumes:
      - ./create_multiple_databases.sh:/docker-entrypoint-initdb.d/create_multiple_databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d dev-database"]
      interval: 10s
      timeout: 5s
      retries: 20