version: "3"
services:
  postgres-dev:
    container_name: postgres-dev
    image: "postgres:11.5-alpine"
    env_file:
      - .env
    ports:
      - '5432:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d dev"]
      interval: 10s
      timeout: 5s
      retries: 20
  elixir-app:
    build:
      context: ./
      dockerfile: /ny_times_api/Dockerfile
      args:
        ELIXIR_VERSION: 1.9.1-alpine
        ELIXIR_PORT: 4000
    depends_on:
      ["postgres-dev"]
    links:
      - db:postgres-dev
    environments:
      POSTGRES_HOST: db



        
      

    
