version: "3"
services:
  postgres-dev:
    container_name: postgres-dev
    image: "postgres:11.5-alpine"
    env_file:
      - .env
    ports:
      - '5432:5432'

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d dev"]
      interval: 10s
      timeout: 5s
      retries: 20
    elixir-app:
      container_name: elixir-app
      dockerfile: Dockerfile
      


  